name: Lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@master
    - name: lint
      uses: luke142367/Docker-Lint-Action@v1.0.0
      with:
        target: Dockerfile
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Python Linter
      uses: sunnysid3up/python-linter@v0.1-beta.7
      with:
        source: "src"
        mypy-options: "--ignore-missing-imports --show-error-codes"
